name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [20.x, 22.x, 24.x]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.os }}-${{ matrix.node-version }}
        path: allure-results
        retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Download all allure results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          merge-multiple: true
          path: allure-results
      - name: Generate Allure Report
        run: npx allure-commandline generate allure-results -o allure-report
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report
